app:
  name: "ScheduleApiGo"

server:
  host: "localhost"
  port: "8080"

dataBase:
  typeDatabase: "postgres"   
  stringConnection: "host=localhost user=postgres password=Jkym139413$ dbname=ScheduleDb sslmode=disable"

rabbitConfig:
  host: "localhost"
  port: "5672"
  user: "guest"
  password: "guest"
  queueDeploy: "Job.Schedule.Deploy"
  queueHistory: "Job.Schedule.History"